stages:
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA



deploy:
  image: docker/compose
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og=  $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd redesocial-front &&
                                                                         git pull origin master  --rebase &&
                                                                       docker stop frontend || true && 
                                                                       docker rm frontend || true &&
                                                                       docker-compose up --build -d "                                                                      
  environment:
    name: production
    url: http://redefelicidade.duckdns.org
  only:
    - master
