version: '3'

services:
  node:
    container_name: frontend
    networks: 
      - redefelicidade
    image: node:10
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8081'
    
    
networks:
  redefelicidade:
    external:
      name: redefelicidade