version: '3'

services:
  node:
    container_name: frontend
    networks: 
      - redefelicidade
    image: node:10
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    working_dir: /app
    command: ['npm', 'run', 'serve']
    
networks:
  redefelicidade:
    external:
      name: redefelicidade